blank_issues_enabled: false
contact_links:
  - name: 💬 Genel Soru veya Geri Bildirim
    url: https://github.com/kullanici-adin/makbulut-ecommerce/discussions
    about: Projeyle ilgili genel sorular için tartışma alanını kullanabilirsiniz.
